# Generated by Django 5.2.17 on 2026-08-10 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='certificate_id',
        ),
    ]
